development: &default
  host: "http://localhost:9200/"
  log: true
test:
  host: "http://localhost:9200/"
  network.host: 127.0.0.1
  transport.tcp.port: 9200
  http.port: 9200

production:
  host: "http://localhost:9200/"